# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinquery',
            name='message',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
