# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 07:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200305_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinquery',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter Correct Mobile Number...', regex='^\\d{10}$')]),
        ),
    ]
