# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('front_image', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
