# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200322_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='html_file',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
