# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-23 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='html_file',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='content', max_length=500),
            preserve_default=False,
        ),
    ]
