# Generated by Django 2.2 on 2020-03-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200323_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Admin', max_length=25),
            preserve_default=False,
        ),
    ]
