# Generated by Django 2.2 on 2020-03-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
