# Generated by Django 2.2 on 2020-05-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
