# Generated by Django 2.2 on 2020-06-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='english_slug',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='hindi_slug',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
