# Generated by Django 2.2 on 2020-06-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200617_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
