# Generated by Django 2.2 on 2020-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200617_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='english_slug',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='hindi_slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_available_in_hindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_hash',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(default='English', max_length=10),
        ),
    ]
