# Generated by Django 2.2 on 2020-06-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200617_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_available_in_hindi',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
