# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200308_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='language',
            field=models.CharField(default='a', max_length=25),
            preserve_default=False,
        ),
    ]
