# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='chapter',
            field=models.CharField(max_length=50),
        ),
    ]
