# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200322_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='chapter',
            new_name='chapter_name',
        ),
        migrations.AddField(
            model_name='note',
            name='chapter_no',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
