# Generated by Django 2.2 on 2020-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='chapter_no',
            field=models.IntegerField(),
        ),
    ]
