# Generated by Django 2.2 on 2020-06-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20200401_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
