# Generated by Django 2.2 on 2020-06-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_note_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.CharField(default='Science', max_length=25),
            preserve_default=False,
        ),
    ]
